namespace Sakuno.SQLite
{
    public enum SQLiteResultCode
    {
        Unknown = -1,
        OK,
        Error,
        Internal,
        Perm,
        Abort,
        Busy,
        Locked,
        NoMemory,
        ReadOnly,
        Interrupt,
        IOError,
        Corrupted,
        NotFound,
        Full,
        CantOpen,
        Protocol,
        Empty,
        Schema,
        TooBig,
        Constraint,
        Mismatch,
        Misuse,
        NoLfs,
        Auth,
        Format,
        Range,
        NotADb,
        Notice,
        Warning,
        Row = 100,
        Done,

        NonExtendedMask = 255,
        IoErrRead = 266,
        IoErrShortRead = 522,
        IoErrWrite = 778,
        IoErrFsync = 1034,
        IoErrDirFsync = 1290,
        IoErrTruncate = 1546,
        IoErrFstat = 1802,
        IoErrUnlock = 2058,
        IoErrRdLock = 2314,
        IoErrDelete = 2570,
        IoErrBlocked = 2826,
        IoErrNoMem = 3082,
        IoErrAccess = 3338,
        IoErrCheckReservedLock = 3594,
        IoErrLock = 3850,
        IoErrClose = 4106,
        IoErrDirClose = 4362,
        IoErrShmOpen = 4618,
        IoErrShmSize = 4874,
        IoErrShmLock = 5130,
        IoErrShmMap = 5386,
        IoErrSeek = 5642,
        IoErrDeleteNoEnt = 5898,
        IoErrMmap = 6154,
        IoErrGetTempPath = 6410,
        IoErrConvPath = 6666,
        IoErrVNode = 6922,
        IoErrAuth = 7178,
        LockedSharedCache = 262,
        BusyRecovery = 261,
        BusySnapshot = 517,
        CantOpenNoTempDir = 270,
        CantOpenIsDir = 526,
        CantOpenFullPath = 782,
        CantOpenConvPath = 1038,
        CorruptVtab = 267,
        ReadOnlyRecovery = 264,
        ReadOnlyCantLock = 520,
        ReadOnlyRollback = 776,
        ReadOnlyDbMoved = 1032,
        AbortRollback = 516,
        ConstraintCheck = 275,
        ConstraintCommitHook = 531,
        ConstraintForeignKey = 787,
        ConstraintFunction = 1043,
        ConstraintNotNull = 1299,
        ConstraintPrimaryKey = 1555,
        ConstraintTrigger = 1811,
        ConstraintUnique = 2067,
        ConstraintVtab = 2323,
        ConstraintRowId = 2579,
        NoticeRecoverWal = 283,
        NoticeRecoverRollback = 539,
        WarningAutoIndex = 284,
        AuthUser = 279,
        OkLoadPermanently = 256
    }
}
